import type { MetricDefinition } from "./domain.js";

export const KPI_DEFINITIONS: MetricDefinition[] = [
  {
    id: "bg_to_delivery",
    label: "BG Date to Delivery Date",
    shortLabel: "BG → Delivery",
    fromField: "bg_date",
    toField: "delivery_date",
    computedField: "bg_to_delivery",
    slaDefault: 45,
    dimensions: ["branch_code", "model", "payment_method"],
  },
  {
    id: "bg_to_shipment_etd",
    label: "BG Date to Shipment ETD PKG",
    shortLabel: "BG → Shipment ETD",
    fromField: "bg_date",
    toField: "shipment_etd_pkg",
    computedField: "bg_to_shipment_etd",
    slaDefault: 14,
    dimensions: ["branch_code", "model"],
  },
  {
    id: "etd_to_outlet",
    label: "Shipment ETD PKG to Date Received by Outlet",
    shortLabel: "ETD → Outlet Received",
    fromField: "shipment_etd_pkg",
    toField: "date_received_by_outlet",
    computedField: "etd_to_outlet_received",
    slaDefault: 28,
    dimensions: ["branch_code", "payment_method"],
  },
  {
    id: "outlet_to_reg",
    label: "Date Received by Outlet to Register Date",
    shortLabel: "Outlet Received → Register Date",
    fromField: "date_received_by_outlet",
    toField: "reg_date",
    computedField: "outlet_received_to_reg",
    slaDefault: 7,
    dimensions: ["branch_code"],
  },
  {
    id: "reg_to_delivery",
    label: "Register Date to Delivery Date",
    shortLabel: "Register Date → Delivery",
    fromField: "reg_date",
    toField: "delivery_date",
    computedField: "reg_to_delivery",
    slaDefault: 7,
    dimensions: ["branch_code", "model"],
  },
  {
    id: "bg_to_disb",
    label: "BG Date to Disb. Date",
    shortLabel: "BG → Disbursement",
    fromField: "bg_date",
    toField: "disb_date",
    computedField: "bg_to_disb",
    slaDefault: 60,
    dimensions: ["branch_code", "payment_method"],
  },
  {
    id: "delivery_to_disb",
    label: "Delivery Date to Disb. Date",
    shortLabel: "Delivery → Disbursement",
    fromField: "delivery_date",
    toField: "disb_date",
    computedField: "delivery_to_disb",
    slaDefault: 14,
    dimensions: ["payment_method"],
  },
];
